### ISSUE TITLE
[#1] Client

### ISSUE THREAD

**Issue by Zajancz** [Zajancz/sk2-Bomberman#1]
Here we insert the changes that we have made in the code of client's file

**Comment by szmanda** [comment]
We need to rewrite the client's side Main.cpp. The most important part is for it to only process the entire messages. It would be best to use `epoll` (like we do on the server, to keep it unified).

---

Basically, whet we need is to make it more like what we have on the server side. We could probably even reuse server classes like `Client` (in this instance we would create a single `Client`). we can `override` specific methods if needed.

We would also need an `MessageHandler` it's probably best to reuse server side class, and `override` necessary methods.

**Comment by szmanda** [comment]
I've made major changes to Client side (as I suggested before). For now client side is using classes from `Server` namespace, we probably need to write their equivalents on client's side (possibly inheritance from server classes? overriding methods?)

There still is a lot of work to do...

**Comment by szmanda** [comment]
We need to change the way we handle messages both on the client side [#1], and server side [#2]. Baisically, with the way we encode the structures to a char* to be sent through the network, we cannot be sure if there will be an unexpected `char = 0` (`\n`).

We can rewrite it, so after buffer length allows for reading the message type, we check the length of a given type. Only after the buffer contains the whole message, we read it's contents.

> **Note** With current implementation, one message can be cut in half, and the 'next' one causes unexpected argument on `std::stoi()` call, (Since it's reading the middle of a previous message)

**Comment by szmanda** [comment]
Functions:
- `void setPosition(godot::Vector2 position);` - sends position to the server, refreshes locally stored `GameState`
- `godot::Array getEnemies();` - returns an array of ids
- `godot::Vector2 getEnemyPosition(int id);` - returns a position of given enemy

are now functional and callable from godot

> **Note** We cannot call `setPostion` too often, so not to overwhelm the server, ideally this should be called once per `x` amount of time. If we were to call it as often as possible, we would end up with a huge backlog of expired messages inside server's buffers.
